nelmio_api_doc:
  documentation:
    info:
      title: "Mon API"
      description: "Documentation de mon API Symfony"
      version: "1.0.0"
  areas: # Définit les zones où Swagger sera disponible
    path_patterns:
      - ^/api # S'applique aux routes qui commencent par "/api"
